"""add conversation id

Revision ID: 794a0393b9ca
Revises: d455430cfac6
Create Date: 2025-11-02 03:48:17.218468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '794a0393b9ca'
down_revision: Union[str, None] = 'd455430cfac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_sessions', sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_query_sessions_conversation_id'), 'query_sessions', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_sessions_conversation_id'), table_name='query_sessions')
    op.drop_column('query_sessions', 'conversation_id')
    # ### end Alembic commands ###
