"""add user id to documents

Revision ID: 96c314f16bae
Revises: eb98e141498e
Create Date: 2025-11-16 09:59:50.610405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '96c314f16bae'
down_revision: Union[str, None] = 'eb98e141498e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_groups', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    op.add_column('documents', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # backfill existing rows with a default user_id if necessary
    # Here we assume a default user_id of 'default-user-id' for existing records.
    # Adjust this logic as per your application's requirements.
    op.execute(
        """
        UPDATE document_groups
        SET user_id = 'a2a378f0-f9f6-4fe6-b31b-b329b55af9cb'
        WHERE user_id IS NULL
        """
    )
    op.execute(
        """
        UPDATE documents
        SET user_id = 'a2a378f0-f9f6-4fe6-b31b-b329b55af9cb'
        WHERE user_id IS NULL
        """
    )
    

    # enforce non-null constraint after populating existing rows
    op.alter_column('document_groups', 'user_id', nullable=False)
    op.create_foreign_key(None, 'document_groups', 'users', ['user_id'], ['id'])
    op.alter_column('documents', 'user_id', nullable=False)
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'user_id')
    op.drop_constraint(None, 'document_groups', type_='foreignkey')
    op.drop_column('document_groups', 'user_id')
    # ### end Alembic commands ###
