"""add document_ids column to query sessions

Revision ID: eb98e141498e
Revises: 794a0393b9ca
Create Date: 2025-11-04 19:00:47.216663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'eb98e141498e'
down_revision: Union[str, None] = '794a0393b9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_sessions', sa.Column('document_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_sessions', 'document_ids')
    # ### end Alembic commands ###
